server:
  port: 9797

spring:
  application:
    name: notice-service
  datasource:
    url: jdbc:mysql://localhost:3309/lms?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: user123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none   # Hibernate로 테이블 자동 생성 방지
    show-sql: true
  sql:
    init:
      mode: always      # SQL 초기화 항상 실행

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
