server:
  port: 7979

spring:
  application:
    name: recruitment-service
  data:
    redis:
      port: 6379
      host: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 로깅 설정
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    edu.ct.admin: DEBUG

#api:
#  service:
#    key: 6v8OZeCdxYl0aFV3k9UwkZDTKov50OEPJOILNm7DSSCLHw38daWB8QZJIFjmfBE0X0%2F%2BWrJL90hXrl0TnbmsiQ%3D%3D

api:
  service:
    key: lmNclzwIue7M4FhXxtpNonBSyWscgAIA1OIl5WJgsKYc%2BHtrEc5xrl7OfLuqecUoO6ZHRadeqR5RLuT35qUu6g%3D%3D