server:
  port: 9292

spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://mysql:3306/lms?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: user123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 로깅 설정
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    edu.ct.admin: DEBUG

openai:
  api-key: ${OPENAI_API_KEY:default-key}